# Generated by Django 3.1.2 on 2021-05-31 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('PROCESSED', 'PROCESSED')], max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='title',
            field=models.CharField(blank=True, choices=[('Product-A', 'Product A'), ('Product-B', 'Product B'), ('Product-C', 'Product C')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='file_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.fileinfo'),
        ),
    ]
